### ISSUE TITLE
Huge size difference between WASM and WASI

### ISSUE THREAD

**Issue by TrivialDem** [Craig-Macomber/lol_alloc#5] opened 2023-07-12 09:26 UTC
Hello, I am trying to the `FreeList` allocator provided by the crate to see its benefit over the standard allocator.
When compiling to `wasm32-unknown-unknown` with the provided example I get an output size of `808o`, however when compiling to `wasm32-wasi` the output size grows up to `30Ko` which is huge. I thought this might be an overhead of WASI in general, though when not using the allocator the size is similar to the one compiled to "standard" WASM.
I used `lto = true`, `opt-level="z"`, `panic="abort"` and `strip = true`, is there a way to further reduce the size ? 
For more information, I've compared the `wat` of each file and the WASI one makes more calls while the WASM one just puts `unreachable` statements. I don't know if this could help.
Thank you

**Comment by Craig-Macomber** [comment] 2023-07-13 01:19
I haven't tried WASI yet, but one thing that would be good to test for comparison is using `FailAllocator`, which just fails all allocations. It won't work of course, but it would be good for the size comparison. If that's not tiny, I suspect the size issue is either general WASI overhead or some issue removing unused code (like the other allocators).

**Comment by TrivialDem** [comment] 2023-07-13 17:43
For size comparison, when using `FailAllocator` the output for `wasm32-unknown-unknown` takes up `147o` while the output for `wasm32-wasi` takes `22Ko`. It might be a global overhead whenever an allocator is specified and an allocation needed.

**Comment by Craig-Macomber** [comment] 2023-07-14 04:01
It might be helpful to compare to a minimal application with no allocator  (if that possible: maybe a no-std app?)?
It that's doable, it could help confirm if using lol_alloc and its allocator is the source of the size or not.

Another idea is hard coding the FailAllocator into your project instead of importing it from lol_alloc to see if there is some overhead coming from importing lol_alloc (maybe the dead code elimination is failing to remove something else thats in the crate?).

I haven't use it but maybe https://github.com/rustwasm/twiggy could help determine whats causing the extra size.

**Comment by Craig-Macomber** [comment] 2024-02-24 03:48
I don't think this issue was related to lol_alloc, however the 0.4.1 does have a code size improvement that might help reduce the occurrence of panic related code in cases that dynamically allocate.

I'm going to close this for now, but if you can confirm the issue is really due to lol_alloc and not fixed by 0.4.1 let me know and I can reopen the issue.

**Closed as completed by Craig-Macomber** 2024-02-24 03:48 UTC
